# lib/apple_sdk_mac/round_trip/round_trip_test_generator.rb
# frozen_string_literal: true

module AppleSDKMac
  module RoundTrip
    # GlueStore に永続化する自走 test-unit ファイルを生成する。committed glue
    # (<symbol>.swift) を team/CI が claude -p 無しで再コンパイル + round-trip 再検証
    # できるよう、driver_inputs (call_expr / invoke_args / value_kind / setter 系) を
    # bake-in する。検証は ProductionRunner に委ね、report は test-unit の assert に乗せる。
    module RoundTripTestGenerator
      module_function

      # @param driver_inputs [Hash] call_expr/invoke_args/value_kind (+setter 系)
      # @return [String] test-unit ソース
      def generate(framework:, symbol:, driver_inputs:)
        di = driver_inputs
        klass = "RoundTrip#{camelize(symbol[:name])}Test"
        setter = di[:value_kind].to_sym == :setter
        setter_keys = setter ? <<~RB.chomp : ""

          ,
                   read_expr: #{di[:read_expr].inspect},
                   set_expr: #{di[:set_expr].inspect},
                   set_value: #{di[:set_value].inspect}
        RB

        <<~RUBY
          # Auto-generated by rb-apple-sdk-mac. Re-verifies the committed glue
          # round-trips (no claude -p needed). Gate: RB_APPLE_SDK_MAC_POC=1.
          # frozen_string_literal: true
          require "test/unit"
          require "tmpdir"
          require "apple_sdk_mac"
          require "apple_sdk_mac/round_trip/production_runner"
          require "apple_sdk_mac/glue_compiler/swiftc_invoker"

          class #{klass} < Test::Unit::TestCase
            FRAMEWORK = #{framework.to_s.inspect}
            CALL_EXPR = <<~'SWIFT'.chomp
          #{indent(di[:call_expr].to_s, 4)}
            SWIFT
            SYMBOL = {
              name: #{symbol[:name].to_s.inspect},
              call_expr: CALL_EXPR,
              invoke_args: #{(di[:invoke_args] || []).inspect},
              value_kind: #{di[:value_kind].to_sym.inspect}#{setter_keys}
            }
            # sibling committed glue: <symbol>_round_trip_test.rb -> <symbol>.swift
            GLUE_SWIFT = __FILE__.sub(/_round_trip_test\\.rb\\z/, ".swift")

            def setup
              omit "set RB_APPLE_SDK_MAC_POC=1" unless ENV["RB_APPLE_SDK_MAC_POC"] == "1"
              omit "committed glue missing: \#{GLUE_SWIFT}" unless File.exist?(GLUE_SWIFT)
            end

            def test_round_trip_green
              exported = File.read(GLUE_SWIFT)[/public\\s+func\\s+(glue_[A-Za-z0-9_]+)/, 1]
              flunk "no exported glue function in \#{GLUE_SWIFT}" unless exported
              Dir.mktmpdir do |dir|
                dylib = File.join(dir, "glue.dylib")
                ok, err = AppleSDKMac::GlueCompiler::SwiftcInvoker.new.compile(
                  source_path: GLUE_SWIFT, dylib_path: dylib,
                  runtime_dylib_path: nil, module_search_paths: []
                )
                omit "glue recompile failed: \#{err}" unless ok
                outcome = AppleSDKMac::RoundTrip::ProductionRunner.new.run(
                  framework: FRAMEWORK, symbol: SYMBOL, dylib: dylib, exported: exported
                )
                assert_true outcome.green?, outcome.detail
              end
            end
          end
        RUBY
      end

      # symbol 名を Swift/Ruby 識別子に使える CamelCase に。非英数は単語境界扱い。
      def camelize(name)
        name.to_s.split(/[^A-Za-z0-9]+/).reject(&:empty?).map { |w| w[0].upcase + w[1..].to_s }.join
      end

      def indent(text, n)
        pad = " " * n
        text.each_line.map { |l| l.strip.empty? ? l : pad + l }.join
      end
    end
  end
end
