# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in rb-apple-sdk-knowledge.gemspec
gemspec

gem "irb"
gem "rake", "~> 13.0"
gem "ruby-progressbar", "~> 1.13"

gem "test-unit", "~> 3.0"

gem "rubocop", "~> 1.21"
